# Generated by Django 5.1.7 on 2025-03-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_aluno', models.CharField(max_length=50, verbose_name='Digite o primeiro nome do aluno')),
                ('last_name_aluno', models.CharField(max_length=50, verbose_name='Digite o sobrenome do aluno')),
                ('phone_number_aluno', models.CharField(max_length=15, verbose_name='Digite o N° de celular (xx) xxxxx-xxxx')),
                ('email_aluno', models.EmailField(max_length=100, verbose_name='Digite o Email do aluno')),
                ('cpf_aluno', models.CharField(max_length=11, unique=True, verbose_name='Informe o CPF do aluno')),
                ('birthday_aluno', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_prof', models.CharField(max_length=50, verbose_name='Digite o primeiro nome do professor')),
                ('last_name_prof', models.CharField(max_length=50, verbose_name='Digite o sobrenome do professor')),
                ('phone_number_prof', models.CharField(max_length=15, verbose_name='Digite o N° de celular (xx) xxxxx-xxxx')),
                ('email_prof', models.EmailField(max_length=100, verbose_name='Digite o Email do professor')),
                ('cpf_prof', models.CharField(max_length=11, unique=True, verbose_name='Informe o CPF do professor')),
                ('birthday_prof', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15, verbose_name='Digite o N° do celular (xx) xxxxx-xxxx')),
                ('email', models.EmailField(max_length=100, verbose_name='Email do responsável')),
                ('adress', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='Informe o CPF do responsável')),
                ('birthday', models.DateField()),
            ],
        ),
    ]
