# Generated by Django 5.1.7 on 2025-03-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='class_choices',
            field=models.CharField(blank=True, choices=[('1A', '1° ano A'), ('1B', '1° ano B'), ('1C', '1° ano C'), ('2A', '2° ano A'), ('2B', '2° ano B'), ('2C', '1° ano C'), ('3A', '3° ano A'), ('3B', '3° ano B'), ('3C', '3° ano C')], max_length=2),
        ),
    ]
