# Generated by Django 5.2 on 2025-06-13 14:13

import django.db.models.deletion
import school.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complet_name_aluno', models.CharField(max_length=100, verbose_name='Nome completo do aluno')),
                ('phone_number_aluno', models.CharField(max_length=15, validators=[school.validators.validar_telefone], verbose_name='Telefone (xx) xxxxx-xxxx')),
                ('matricula_aluno', models.CharField(max_length=50, verbose_name='Matrícula do aluno')),
                ('email_aluno', models.EmailField(max_length=100, verbose_name='Email do aluno')),
                ('cpf_aluno', models.CharField(max_length=11, unique=True, validators=[school.validators.validar_cpf], verbose_name='CPF do aluno')),
                ('birthday_aluno', models.DateField()),
                ('class_choices', models.CharField(blank=True, choices=[('1A', '1° ano A'), ('1B', '1° ano B'), ('1C', '1° ano C'), ('2CN', '2° ano CN'), ('2DS', '2° ano DS'), ('2JG', '2° ano JOGOS'), ('3CN', '3° ano CN'), ('3DS', '3° ano DS'), ('3JG', '3° ano JOGOS')], max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Aluno',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_subject', models.CharField(choices=[('DS', 'Desenvolvimento de Sistemas'), ('CN', 'Ciencias da Natureza'), ('DJ', 'Desenvolvimento de Jogos'), ('MAT', 'Matematica'), ('CH', 'Ciencias Humanas'), ('LG', 'Linguagens')], max_length=50, verbose_name='Selecione a Materia desejada')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplina',
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complet_name', models.CharField(max_length=50, verbose_name='Nome completo do responsável')),
                ('phone_number', models.CharField(max_length=15, validators=[school.validators.validar_telefone], verbose_name='Telefone (xx) xxxxx-xxxx')),
                ('email', models.EmailField(max_length=100, verbose_name='Email do responsável')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[school.validators.validar_cpf], verbose_name='CPF do responsável')),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('1°', '1° ano'), ('2°', '2° ano'), ('3°', '3° ano')], max_length=50, verbose_name='Turma ')),
                ('itinerary_name', models.CharField(choices=[('N', 'Nenhum'), ('CN', 'Ciências da Natureza'), ('DS', 'Desenvolvimento de Sistemas'), ('DJ', 'DEsenvolvimento de Jogos')], max_length=50, verbose_name='Itinerário a qual essa turma pertence')),
                ('godfather_prof', models.CharField(max_length=50, verbose_name='Professor padrinho da turma')),
                ('class_representante', models.CharField(max_length=50, verbose_name='Representante da turma')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turma',
            },
        ),
        migrations.CreateModel(
            name='AlunoNotas',
            fields=[
            ],
            options={
                'verbose_name': 'Notas por Aluno',
                'verbose_name_plural': 'Notas por Aluno',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('school.aluno',),
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato_assinado', models.BooleanField(default=False, verbose_name='Contrato Assinado')),
                ('arquivo_assinado', models.FileField(blank=True, null=True, upload_to='contratos_assinados/', verbose_name='Arquivo do Contrato Assinado')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.aluno')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contrato',
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_lancamento', models.DateField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='school.aluno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='school.materia')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Nota',
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complet_name_aluno', to='school.responsavel'),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complet_name_prof', models.CharField(max_length=50, null=True, verbose_name='Nome completo do professor')),
                ('materia_prof', models.CharField(max_length=50, verbose_name='Matéria lecionada pelo professor')),
                ('phone_number_prof', models.CharField(max_length=15, validators=[school.validators.validar_telefone], verbose_name='Telefone (xx) xxxxx-xxxx')),
                ('matricula_prof', models.CharField(max_length=50, verbose_name='Matrícula do professor')),
                ('email_prof', models.EmailField(max_length=100, verbose_name='Email do professor')),
                ('cpf_prof', models.CharField(max_length=11, null=True, unique=True, validators=[school.validators.validar_cpf], verbose_name="'CPF do professor")),
                ('birthday_prof', models.DateField(max_length=10, verbose_name='data de nascimentp do professor')),
                ('subject_choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materia', to='school.materia')),
                ('class_choices', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='padrinho', to='school.turmas')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professor',
            },
        ),
    ]
