# Generated by Django 5.2 on 2025-08-13 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_aluno_class_choices_alter_materia_name_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='class_choices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.turmas', verbose_name='Turma do aluno'),
        ),
    ]
