# Generated by Django 5.2 on 2025-08-13 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_aluno_class_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da chamada')),
                ('status', models.CharField(choices=[('P', 'Presente'), ('F', 'Faltou')], max_length=1, verbose_name='Presença/Falta')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltas', to='school.aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltas', to='school.turmas')),
            ],
            options={
                'verbose_name': 'Falta',
                'verbose_name_plural': 'Faltas',
                'unique_together': {('data', 'turma', 'aluno')},
            },
        ),
    ]
