# Generated by Django 5.2 on 2025-08-13 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_falta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data da advertência')),
                ('motivo', models.TextField(verbose_name='Motivo da advertência')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertencias', to='school.aluno')),
            ],
        ),
    ]
