# Generated by Django 5.2 on 2025-08-13 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_advertencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertencia',
            name='data',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='DocumentoAdvertencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentoadvertencia_assinado', models.BooleanField(default=False, verbose_name='Documento de Advertência Assinado')),
                ('documento_assinado', models.FileField(blank=True, null=True, upload_to='documentos_advertencia/', verbose_name='Arquivo do Documento de Advertência Assinado')),
                ('advertencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.advertencia')),
            ],
            options={
                'verbose_name': 'Documento de Advertência',
                'verbose_name_plural': 'Documento de Advertência',
            },
        ),
    ]
