# Generated by Django 5.1.7 on 2025-08-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_advertencia_data_documentoadvertencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='falta',
            options={'verbose_name': 'Chamada', 'verbose_name_plural': 'Chamada'},
        ),
        migrations.AddField(
            model_name='nota',
            name='bimestre',
            field=models.CharField(choices=[('1', '1° Bimestre'), ('2', '2° Bimestre'), ('3', '3° Bimestre'), ('4', '4° Bimestre')], default='1', max_length=1, verbose_name='Bimestre'),
        ),
    ]
