# Generated by Django 5.1.7 on 2025-08-29 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_falta_options_nota_bimestre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='bimestre',
        ),
    ]
